### ISSUE TITLE
inference.py

### ISSUE THREAD

**Issue by debasmitdas** [haoningwu3639/StoryGen#10]
In the inference.py, the setting seems to be autoregressive and requires and initial image. How do we set it to story generation instead of continuation ?

**Comment by UestcJay** [comment]
I also have questions about this. Emmm, I do not find the  story generation setting. For continuation, sometimes, there will be inconsistency in the pictures and characters generated before and after. @haoningwu3639 @Verg-Avesta

**Comment by Verg-Avesta** [comment]
For story generation, please use  **stage = 'no'** in inference.py to generate the first frame in a single-frame manner.

**Comment by UestcJay** [comment]
thanks for your reply! when I use stage = 'no' in inference.py, if I set `prev_p` and `ref_image` to empty lists, the code will report an error. How should I set it? Can you give me some advice?

**Comment by Verg-Avesta** [comment]
Please use a random ``prev_p`` and ``ref_image`` instead. The model will not extract and attend to their features when ``stage = 'no'``.

**Comment by UestcJay** [comment]
I used an example in the supplementary material of the paper. The effect does not seem to be very similar to that in the paper.
Can you give me some advice?
 I set num_inference_steps = 40
 guidance_scale = 7
image_guidance_scale = 3.5
num_sample_per_prompt = 1
mixed_precision = "fp16"
<img width="416" alt="微信截图_20240313163403" src="https://github.com/haoningwu3639/StoryGen/assets/37372259/a49b0c32-ab07-4b8c-9faf-f02cded2aafe">
<img width="877" alt="微信截图_20240313163346" src="https://github.com/haoningwu3639/StoryGen/assets/37372259/6ae17f05-641b-42f3-9092-45e0432c0139">

**Comment by haoningwu3639** [comment]
As mentioned in the Method and Dataset sections of our paper, for existing text-to-image models, 'descriptive text' is more suitable to serve as a prompt than 'narrative story text'. Thus, we also mentioned in our paper that we should use ChatGPT or GPT-4 (or an open-source LLM such as LLaMA) to convert the storylines into corresponding descriptions as input to the model. We recommend you do the same.

**Comment by chwjshlwel** [comment]
when I use the  stage = 'no', the following error occurs.
Traceback (most recent call last):
  File "D:\AIGC\StoryGen-master\inference.py", line 139, in <module>
    test(pretrained_model_path, 
  File "D:\AIGC\StoryGen-master\inference.py", line 103, in test
    output = pipeline(
  File "C:\Users\chwj0\miniconda3\envs\ldm\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "D:\AIGC\StoryGen-master\model\pipeline.py", line 443, in __call__
    for k,v in img_conditions[0].items():
AttributeError: 'NoneType' object has no attribute 'items'

**Comment by chwjshlwel** [comment]
> I used an example in the supplementary material of the paper. The effect does not seem to be very similar to that in the paper. Can you give me some advice? I set `num_inference_steps = 40` `guidance_scale = 7` `image_guidance_scale = 3.5` `num_sample_per_prompt = 1` `mixed_precision = "fp16"` <img alt="微信截图_20240313163403" width="416" src="https://private-user-images.githubusercontent.com/37372259/312373450-a49b0c32-ab07-4b8c-9faf-f02cded2aafe.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE0NjI5MDksIm5iZiI6MTcxMTQ2MjYwOSwicGF0aCI6Ii8zNzM3MjI1OS8zMTIzNzM0NTAtYTQ5YjBjMzItYWIwNy00YjhjLTlmYWYtZjAyY2RlZDJhYWZlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI2VDE0MTY0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYxNTU2ODdjOTA3MTEwNGZiYzM3NmFkNTcyOTI1ZmIxOWQyN2Y0OWY3YTYyMTM4OGFmZGEzNDViNTYyODBmM2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.IqVA8V2OhWwvK3L6ssybkpEdbcy8fFzFJy-gcWs1R24"> <img alt="微信截图_20240313163346" width="877" src="https://private-user-images.githubusercontent.com/37372259/312373546-6ae17f05-641b-42f3-9092-45e0432c0139.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE0NjI5MDksIm5iZiI6MTcxMTQ2MjYwOSwicGF0aCI6Ii8zNzM3MjI1OS8zMTIzNzM1NDYtNmFlMTdmMDUtNjQxYi00MmYzLTkwOTItNDVlMDQzMmMwMTM5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI2VDE0MTY0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ1NjEzNjZiZjM3NTAxMmU4MDlhMTIxZTFmY2ZhMzhkMGVjODkyM2UxMjQxYTVmZDVkZmJiZTA3MjA5NWJkZGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.RBKUmsSbRvv5FD6aFMmZ1Czi-368bDJiPsePFo06S7k">

I don't know how to make a story like this and the Fig. 1 in the paper. When I set stage = 'no', the above error comes.

**Comment by Verg-Avesta** [comment]
Please refer to https://github.com/haoningwu3639/StoryGen/issues/14#issuecomment-2030970209.

**Comment by Verg-Avesta** [comment]
Sorry, I just found a bug in pipeline.py and fixed it. Please use the new pipeline.py .
Now when using **stage='no'** with a random **prev_p** and **ref_image**, you can generate the correct result.

**Comment by cloverGithub** [comment]
Hi, i managed to get a relatively decent image for reference_image.png but very noisy image for referenced.png. May i know why is that so, and how to resolve? Thanks.
![reference_image](https://github.com/haoningwu3639/StoryGen/assets/45625319/7939a2ee-a173-47e9-9019-f0e5c81d4f75)
![output](https://github.com/haoningwu3639/StoryGen/assets/45625319/c0a71a07-694c-4908-856d-a90962a80d30)

**Comment by haoningwu3639** [comment]
We haven't met this problem before, but we recommend you check whether you have loaded the pre-trained checkpoints correctly. It seems that the model is not working correctly.
