### ISSUE TITLE
inference CUDA out of memory

### ISSUE THREAD

**Issue by UestcJay** [haoningwu3639/StoryGen#11]
thanks for your work! When I run inference.py, `ref_image` in inference.py dose not exist! so I change as follow:
```
prompt = "The curly puppy is running after the flying dragon."
    prev_p = ["The curly puppy", "The flying dragon."]
    ref_image = ["./data/image/00001.png", 
                 "./data/image/00002.png"]
```
After I run `CUDA_VISIBLE_DEVICES=0 accelerate launch inference.py`,  it shows `CUDA out of memory.`  My GPU is 80G A800. Can you give me some suggestions

**Comment by haoningwu3639** [comment]
emm... I haven't met such problems. RTX 3090 is usually sufficient for inference. I recommend checking that 'xformers' work properly and also reducing the 'num_sample_per_prompt' for inference.
