### ISSUE TITLE
Access to Model Checkpoint

### ISSUE THREAD

**Issue by saemee007** [haoningwu3639/StoryGen#16]
I tried accessing the model checkpoint link, but it seems that the model checkpoint has not been uploaded. Is there any way for me to access it?

Additionally, I'm very interested in your research, and I'm truly impressed by your efforts and contributions.

**Comment by haoningwu3639** [comment]
sorry? I do have uploaded the checkpoints, please refer to https://huggingface.co/haoningwu/StoryGen/tree/main/checkpoint_StorySalon and https://huggingface.co/haoningwu/StoryGen/tree/main/checkpoint_COCO for them.
And thanks for your reminder, I also create and paste a README.md in the huggingface repository.
