### ISSUE TITLE
Unable to download youtube data, can you provide the corresponding key frames?

### ISSUE THREAD

**Issue by sixiaozheng** [haoningwu3639/StoryGen#17]
Hello, I am very interested in your work. I'm having trouble downloading the data and I'd like your help.

I cannot download "video_url" in metadata.json through the following command.

`youtube-dl --write-auto-sub -o 'file\%(title)s.%(ext)s' -f 135 https://youtu.be/JBzHBp6kfMo
[youtube] JBzHBp6kfMo: Downloading webpage
ERROR: JBzHBp6kfMo: YouTube said: Unable to extract video data`

This video is a private video.

**Comment by haoningwu3639** [comment]
Please refer to https://github.com/haoningwu3639/StoryGen/issues/13#issuecomment-2018199255, we recommend you skip the inaccessible URLs, and use other data.
As we mentioned in the LICENSE and Copyright part of the README, considering YouTube's potential copyright issues, we are only able to provide the URLs of the videos we downloaded. But we also provide a complete data processing pipeline. You can re-capture suitable videos on YouTube to download, and use the tools we provide to process them into suitable training data.
