### ISSUE TITLE
OSError: Error no file named pytorch_model.bin, tf_model.h5, model.ckpt.index or flax_model.msgpack found in directory checkpoint_StorySalon/

### ISSUE THREAD

**Issue by usman-bsee** [haoningwu3639/StoryGen#19]
I am trying to run inference on the code, but there is this error that requires 3 files and I am not able to find those files. Kindly, guide me where to find those files? Or do I have to train the model first? I am just running inference by downloading the checkpoints of StorySalon from the provided link.
https://huggingface.co/haoningwu/StoryGen/tree/main

**Comment by haoningwu3639** [comment]
We haven't encountered this problem before, but it seems that there may be a problem with the loading path. 
For example, if you need to use a model trained on StorySalon data, you need to load /your_path/ckpt/chekpoint/StorySalon, instead of /your_path/ckpt.
