### ISSUE TITLE
How to download PDF data and split dataset?

### ISSUE THREAD

**Issue by siyuch-fdu** [haoningwu3639/StoryGen#20]
The readme mentioned that:

> Data from Open-source Libraries
For the open-source PDF data, you can directly download the frames, corresponding masks, description and narrative from [StorySalon](https://huggingface.co/datasets/haoningwu/StorySalon).

but I can't find PDF data from that link.

Also, after processing the data, how to split them to train and val dataset. What is the proportion between them?

**Comment by haoningwu3639** [comment]
Emm, we have already provided frames, masks, and descriptions in the zip files in the HuggingFace repository (https://huggingface.co/datasets/haoningwu/StorySalon/blob/main/StorySalon.zip). And the indices of test data are also included, or you can find them in https://github.com/haoningwu3639/StoryGen/blob/master/data/PDF_test_set.txt and https://github.com/haoningwu3639/StoryGen/blob/master/data/video_test_set.txt.

**Comment by siyuch-fdu** [comment]
Thank you very much for your generous reply! Looking forward to your new work!
