### ISSUE TITLE
Clean up of the env yaml file

### ISSUE THREAD

**Issue by TimandXiyu** [haoningwu3639/StoryGen#21]
It seems that the env yaml file is just auto generated? leaving many package that is not used to be installed. Can they authors check what packages are really needed because the current yaml file also triggers multiple errors regarding the version of packages to be installed. (auto-generated version limits are being too tight)

**Comment by haoningwu3639** [comment]
Sorry for the inconvenience, I recommend installing key dependencies such as pytorch, diffusers, accelerate, xformers, etc. according to our README file.
I will update a new, more concise yaml file over time.

**Comment by TimandXiyu** [comment]
> Sorry for the inconvenience, I recommend installing key dependencies such as pytorch, diffusers, accelerate, xformers, etc. according to our README file. I will update a new, more concise yaml file over time.

Hi, thanks for replying. Another question as I want to replicate your training: many toutube videos being used in the dataset is no longer public, making them not ready for downloading. Can the authors release that portion of data, or maybe this is restricted due to some regulations?
