### ISSUE TITLE
FileNotFoundError: No such file or directory: './StorySalon/image_inpainted_finally_checked'

### ISSUE THREAD

**Issue by sixiaozheng** [haoningwu3639/StoryGen#23]
I encountered a FileNotFoundError while trying to run the dataset.py script. It seems that the directory ./StorySalon/image_inpainted_finally_checked is missing. Below is the detailed error message:

`  File "/projects/StoryGen/dataset.py", line 143, in __init__
    video_folders = sorted(os.listdir(self.video_image_dir)) # 00001
FileNotFoundError: [Errno 2] No such file or directory: './StorySalon/image_inpainted_finally_checked'
`

**Comment by haoningwu3639** [comment]
We have provided the download link summary of the dataset (meta-data.json) in the repo and provided the pipeline to obtain the corresponding text and mask.
The dataset has already uploaded to HuggingFace, you can download it from https://huggingface.co/datasets/haoningwu/StorySalon
Please refer to https://github.com/haoningwu3639/StoryGen/issues/20#issuecomment-2076365114 for more details.
