### ISSUE TITLE
story to images

### ISSUE THREAD

**Issue by zulihit** [haoningwu3639/StoryGen#33]
Thank you for your wonderful work. May I ask if it is possible for me to input a story and output a series of images. How can I implement this function

**Comment by haoningwu3639** [comment]
Well, since different people input stories in various ways (direct input or calling GPT to generate), we did not implement a function/interface for non-researchers.
But you can divide the story into prompts one by one, and generate the story frames step by step in an auto-regressive way by using the functions in 'inference.py'. 
You can also further encapsulate a loop based on it to auto-regressively generate the image sequence corresponding to the entire story at once.

**Comment by zulihit** [comment]
> Well, since different people input stories in various ways (direct input or calling GPT to generate), we did not implement a function/interface for non-researchers. But you can divide the story into prompts one by one, and generate the story frames step by step in an auto-regressive way by using the functions in 'inference.py'. You can also further encapsulate a loop based on it to auto-regressively generate the image sequence corresponding to the entire story at once.

Thank you for your reply. I noticed in inference.py that there is the following code:

python
复制代码
prompt = "The white cat is running after the black-haired man."
prev_p = ["The black-haired man", "The white cat."]
ref_image = ["./data/boy.jpg", "./data/whitecat1.jpg"]
I couldn't find the files boy.jpg and whitecat1.jpg in the data folder. Could you please provide a prompt list and ref_images related to Figure 1 in the paper or another simple story, as well as instructions on how to run it and show the results? I would be very grateful.

**Comment by zulihit** [comment]
> Well, since different people input stories in various ways (direct input or calling GPT to generate), we did not implement a function/interface for non-researchers. But you can divide the story into prompts one by one, and generate the story frames step by step in an auto-regressive way by using the functions in 'inference.py'. You can also further encapsulate a loop based on it to auto-regressively generate the image sequence corresponding to the entire story at once.

Thank you for your reply. I noticed in inference.py that there is the following code:

prompt = "The white cat is running after the black-haired man."
prev_p = ["The black-haired man", "The white cat."]
ref_image = ["./data/boy.jpg", "./data/whitecat1.jpg"]
I couldn't find the files boy.jpg and whitecat1.jpg in the data folder. Could you please provide a prompt list and ref_images related to Figure 1 in the paper or another simple story, as well as instructions on how to run it and show the results? I would be very grateful.

**Comment by zulihit** [comment]
Thank you for your reply. May I inquire about the correct operation of inferrence.py, as I noticed that the two reference images are not in the data folder.
________________________________
发件人: Haoning Wu ***@***.***>
发送时间: 星期三, 七月 24, 2024 10:00:14 下午
收件人: haoningwu3639/StoryGen ***@***.***>
抄送: zuli ***@***.***>; Author ***@***.***>
主题: Re: [haoningwu3639/StoryGen] story to images (Issue #33)


Well, since different people input stories in various ways (direct input or calling GPT to generate), we did not implement a function/interface for non-researchers.
But you can divide the story into prompts one by one, and generate the story frames step by step in an auto-regressive way by using the functions in 'inference.py'.
You can also further encapsulate a loop based on it to auto-regressively generate the image sequence corresponding to the entire story at once.

―
