### ISSUE TITLE
Testset

### ISSUE THREAD

**Issue by VisionLover** [haoningwu3639/StoryGen#37]
Hi, In one of the issues, you said that the test data does not need data processing. Is `MiniGPT-v2` or `TextBind` applied to this data? What about the results reported in the article? Because many of the images in the test set have not very good captions, which I think are more similar to the story-level narration that you mentioned in the paper.

**Comment by haoningwu3639** [comment]
The dataset we released contains narration and descriptions generated by TextBind, which can be used directly. We also tried MiniGPT-v2. To be honest, it generates better descriptions, but it does not perform as well as TextBind in subsequent generation tasks, so we still use TextBind by default.
