### ISSUE TITLE
How metadata is used in extracting frames ?

### ISSUE THREAD

**Issue by debasmitdas** [haoningwu3639/StoryGen#4]
Can anybody pinpoint how metadata.json is being used in extracting the frames ? I cannot find how it is being used to extract keyframes from videos. Also, if one has already processed the frames from the videos that would be great and can share here

**Comment by Verg-Avesta** [comment]
You can use  ```python ./data_process/extract.py``` to extract all the keyframes and their corresponding subtitles in the videos. Then you can select the keyframes with the correct timestamp as shown in metadata.json and only keep them, without the need to run ```CUDA_VISIBLE_DEVICES=0 python ./data_process/dup_remove.py```.

For example, if you have extracted all the keyframes of video _"After the Fall (kids books read aloud) Humpty Dumpty Dan Santat"_ , you can select the keyframes in the frame_list and only keep them. Considering that the video_id might be different, you can keep the frame with timestamp _"0-0-14-814"_ based on the frame _"000000_keyframe_0-0-14-814.jpg"_ from frame_list.
