### ISSUE TITLE
Stage's option

### ISSUE THREAD

**Issue by 0Tzero** [haoningwu3639/StoryGen#41]
Hello!Thanks for your code and checkpoint!Could you please explain what "multi-image-condition" and "auto-regressive" mean in the context of the model?

**Comment by haoningwu3639** [comment]
Please refer to the Figure of model architecture in our paper and the appendix, where we provide another model architecture for experiments conducted on the MS-COCO dataset. 
The **multi-image condition** and **auto-regressive** settings correspond to these two different experimental setups, respectively.
