### ISSUE TITLE
Downloading private videos

### ISSUE THREAD

**Issue by debasmitdas** [haoningwu3639/StoryGen#5]
Has anybody had success in downloading the private videos in the list ? It seems a lot of the videos were rejected due to them being private. What command or script is being used ?

**Comment by ChengKai-kk** [comment]
I do have the same problem,but I skipped all the private videos in the list

**Comment by debasmitdas** [comment]
@ChengKai-kk Thanks for mentioning. With the current code and after the two stage training, are you able to generate reasonable visual outputs for a storybook ?

**Comment by haoningwu3639** [comment]
Sorry for the late reply. Given YouTube's potential copyright rules, we can only provide their download URLs, so users can download videos that are still available, or any other 'storytelling videos'. Then you can use the data processing pipeline provided by us to get the data suitable for our model training. In addition, we have updated the open-source book data in the dataset, which can be downloaded directly from our given huggingface repository.
