### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by debasmitdas** [haoningwu3639/StoryGen#8]
Can you add a license for the dataset and code? Also, it is specified that the EBooks are under CC-BY license, but it's unclear if they only downloaded YouTube videos that are under CC-BY license as well. Is this information available?

**Comment by debasmitdas** [comment]
@haoningwu3639. Thank you for releasing the checkpoint. Could you specify the license for the checkpoint and dataset ? We would like to suggest MIT license if possible.

**Comment by haoningwu3639** [comment]
Thanks for the advice, we have added the license for the project, and you can refer to our README for detailed licenses for different parts.
The code and checkpoints in this repository are under MIT license.
The open-source books in the StorySalon dataset come from multiple online open-source libraries (please refer to the Appendix of our paper for more details), and they are all under CC-BY 4.0 license.
It should be noted that, for the data extracted from the video data, we only provide YouTube URLs and data processing pipelines, if you wish to use them for commercial purposes, we recommend that you obey the relevant regulations of YouTube.
